package com.gamma.catalog;

/**
 * Where a {@link Description} came from, in descending order of authority.
 *
 * <p>The declaration order <em>is</em> the rank: {@link #MANUAL} (0) outranks {@link #AI} (1)
 * outranks {@link #DEDUCED} (2) outranks {@link #NONE} (3). {@link Description#mergePreferring}
 * relies on {@link #ordinal()} so a higher-authority description never loses to a lower one —
 * in particular, operator-authored prose is sticky against re-derivation and AI suggestion.
 */
public enum Provenance {
    /** Hand-authored by an operator (in the schema {@code .toon} or {@code *_meta.toon}). */
    MANUAL,
    /** Generated by an AI {@code DescriptionProvider} (wired in the agent module at M3). */
    AI,
    /** Seeded from a heuristic (e.g. column-name pattern) by a built-in provider. */
    DEDUCED,
    /** No description available. */
    NONE
}
